# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
