# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_gravatar'),
        ('article', '0002_auto_20160121_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedArticle',
            fields=[
                ('ext_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
