# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('article', '0005_unlikedlikedarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAction',
            fields=[
                ('ext_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='likedarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='likedarticle',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='unlikedlikedarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='unlikedlikedarticle',
            name='profile',
        ),
        migrations.DeleteModel(
            name='LikedArticle',
        ),
        migrations.DeleteModel(
            name='UnlikedLikedArticle',
        ),
    ]
