# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20160130_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleaction',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
