# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gravatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
